app = "nova-stream-discord"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  NOVA_WEBSITE_URL = "https://hazeyy5.github.io/nova-stream"
  NOVA_GITHUB_URL = "https://github.com/Hazeyy5/nova-stream"
