name = "nova-stream-donations"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
PAYPAL_MODE = "live"
PAYPAL_REDIRECT_URI = "https://nova-stream-donations.contact-delaplacetheo.workers.dev/v1/paypal/callback"

[[d1_databases]]
binding = "DB"
database_name = "nova-donations"
database_id = "4e8be164-f127-4e87-aa5c-3348e0c45b2e"
migrations_dir = "migrations"
